site_name: Keeper
repo_name: Keeper
repo_url: https://github.com/slackhq/Keeper
site_description: "A Gradle plugin that infers Proguard/R8 keep rules for androidTest sources."
site_author: Slack
remote_branch: gh-pages

copyright: 'Copyright &copy; 2020 Slack Technologies, Inc.'

theme:
  name: 'material'
  favicon: images/slack_logo_small.png
  logo: images/slack_logo.png
  palette:
    primary: 'white'
    accent: 'white'
  language: 'en'
  font:
    text: 'Lato'
    code: 'Fira Code'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables
  - mdx_truly_sane_lists

nav:
  - 'Overview': index.md
  - 'Configuration' : configuration.md
  - 'API' : 0.x/keeper-gradle-plugin/index.html
  - 'Changelog' : changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code-of-conduct.md